### ISSUE TITLE
User registered but is unable to restore account

### ISSUE THREAD

**Issue by ana0** [CirclesUBI/circles-myxogastria#158]
Bug report from a user who signed up on Oct 19, 2020, and was given profile url: https://circles.garden/profile/0x5815151E56CeDd6aDdB092bf93a0884a5D0F7bE2.  They were able to go through the signup process enough to receive a profile url, but it seems no entry was made in the `users` table for them

They are willing/aware of the consequences of burning their account and this is the mnemonic:

`aspect cricket universe innocent forest winter crisp media property style gesture ask equal relief organ green setup credit arena wisdom armor liar frost rack`

When this happens during signup, a user should receive feedback that their signup did not work. If they try to log in again, the app should either 1) recover from this state (since they may have already received several trusts) or at minimum 2) better communicate to them that this account is unrecoverable

**Comment by adzialocha** [comment]
Related issue: https://github.com/CirclesUBI/circles-myxogastria/issues/165

**Comment by adzialocha** [comment]
I did some debugging on this and found out that the predicted Safe address is **different** for these accounts when they get restored, the relayer fails with an `404` as this Safe is unknown to it.

I wonder now what causes the relayer to predict the safe address differently:

1. Is the private key different?
2. Did the logic change how the relayer predicts the safe address since the user signed up?

**Comment by adzialocha** [comment]
Here are some scripts reproducing the problem: https://gist.github.com/adzialocha/c622ae5890deee315f658489b85bfc55. I get a different predicted safe than the one actually being used in my official Circles account:

1. Original Safe address of user *adz* with owner `0xaA2F8f57730d41BB145D168F6A689fDDa737a081`:
`0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC`

2. Running node script returning `0xEA4e6a595B378C31cd294019b274391c7aE08aB5`

    ```
    $ node index.js
    safeAddress=0xEA4e6a595B378C31cd294019b274391c7aE08aB5, nonce=175774342029441, address=0xaA2F8f57730d41BB145D168F6A689fDDa737a081
    ```

3. Running python script returning `0x505CcCa1d53028E6e0CDc28b4e8cA7919EA0eeAD`

    ```
    $ python main.py
    0x505CcCa1d53028E6e0CDc28b4e8cA7919EA0eeAD
    ```

**Comment by llunaCreixent** [comment]
Reproduced with my account and got different results:

1. Original Safe address of my user with owner `0x783110347c923b8694EF90D01D70E8f2a62b3720`:
`0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e`

2. Running node script returning `0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e` (correct 😺 )
```bash
$ node index.js
safeAddress=0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e, nonce=256128867579680, address=0x783110347c923b8694EF90D01D70E8f2a62b3720
```


3. Running python script returning `0xB7DEE4c6825b26fFe99B3c02e87FC4Cc20E99339`
```bash
$ python main.py
0xB7DEE4c6825b26fFe99B3c02e87FC4Cc20E99339
```

**Comment by adzialocha** [comment]
> Reproduced with my account and got different results:

That's interesting! So your account got created later than mine, it makes sense that your prediction works (at least when going through the relayer, with the python script we still might use the wrong values, will need to check so they are the same as the relayer uses).

I assume that the prediction for older accounts is wrong because we changed the values used for the prediction at some stage (hard to trace back when exactly, but maybe a few weeks after the launch, maybe when migrating to Kubernetes?).

It looks like that the following parameters are involved in safe address prediction:

```
master_copy_address
proxy_factory_address
salt_nonce
owners
threshold
gas_price
payment_token
payment_receiver
fallback_handler
payment_token_eth_value
fixed_creation_cost
```

It would be cool to find out what current values are the relayer uses on production, then see if we can reproduce that behaviour in the python script to verify its all good. And then the big mystery starts by finding out what value changed for all accounts from "the past" and why, to avoid this happening again :cry: and maybe also to build a solution / fix which gives support for predicting "old" account addresses.

**Comment by adzialocha** [comment]
These are the values used on production currently:

```
master_safe_address = 0x2CB0ebc503dE87CFD8f0eCEED8197bF7850184ae
proxy_factory_address = 0x8b4404DE0CaECE4b966a9959f134f0eFDa636156
salt_nonce = ...
owners = ['...']
threshold = 1
gas_price = 1000000000
payment_token = 0x0000000000000000000000000000000000000000
payment_receiver = 0x0276d6d8fB555894f11d933994154D7C37574746
fallback_handler = 0x0000000000000000000000000000000000000003
payment_token_eth_value = 1.0
fixed_creation_cost = None
```

**Comment by adzialocha** [comment]
Some prediction examples:

```
2021-05-05 15:23:59,458 [INFO] [MainProcess] Safe.build_safe_create2_tx params: 0x2CB0ebc503dE87CFD8f0eCEED8197bF7850184ae 0x8b4404DE0CaECE4b966a9959f134f0eFDa636156 256128867579680 ['0x783110347c923b8694EF90D01D70E8f2a62b3720'] 1 1000000000 0x0000000000000000000000000000000000000000 0x0276d6d8fB555894f11d933994154D7C37574746 0x0000000000000000000000000000000000000003 1.0 None
```

```
2021-05-05 15:22:39,604 [INFO] [MainProcess] Safe.build_safe_create2_tx params: 0x2CB0ebc503dE87CFD8f0eCEED8197bF7850184ae 0x8b4404DE0CaECE4b966a9959f134f0eFDa636156 194074909000304 ['0x82a9a537Af8c3231545ED39CfEd0b0829602C270'] 1 1000000000 0x0000000000000000000000000000000000000000 0x0276d6d8fB555894f11d933994154D7C37574746 0x0000000000000000000000000000000000000003 1.0 None
```

**Comment by adzialocha** [comment]
Using the relayer with the same values returns something else than running the `main.py` gist script:

```
curl -X POST "https://relay.circles.garden/api/v3/safes/predict/" -H  "Content-Type: application/json" -H  "accept: application/json" -H  "X-CSRFToken: k2JXE5nrUpD2IEE0t1NEUacbRPPkgBMi0SiVK2wbk8ZfbkryVYVbzhFHsSXA3B9G" -d '{ "saltNonce": "256128867579680", "owners": ["0x783110347c923b8694EF90D01D70E8f2a62b3720"], "threshold": 1 }'
0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e
```

```
python main.py
0xB7DEE4c6825b26fFe99B3c02e87FC4Cc20E99339
```

**Comment by adzialocha** [comment]
Logging the values from https://github.com/gnosis/gnosis-py/blob/e4616bffa9545afae60b3be4ce89c4c60f987b68/gnosis/safe/safe_create2_tx.py#L99-L118 when running `main.py` locally against production ethereum node:

```
final_safe_setup_data
b'\xb6>\x80\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf6\xc8\xbb\x85\xcc\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02v\xd6\xd8\xfbUX\x94\xf1\x1d\x939\x94\x15M|7WGF\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x1\x104|\x92;\x86\x94\xef\x90\xd0\x1dp\xe8\xf2\xa6+7 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

```
safe_setup_data
b'\xb6>\x80\r\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02v\xd6\xd8\xfbUX\x94\xf1\x1d\x939\x94\x15M|7WGF\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x1\x104|\x92;\x86\x94\xef\x90\xd0\x1dp\xe8\xf2\xa6+7 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

```
magic_gas
231208
```

```
estimated_gas
271342
```

**Comment by llunaCreixent** [comment]
> Using the relayer with the same values returns something else than running the `main.py` gist script:
> 
> ```
> curl -X POST "https://relay.circles.garden/api/v3/safes/predict/" -H  "Content-Type: application/json" -H  "accept: application/json" -H  "X-CSRFToken: k2JXE5nrUpD2IEE0t1NEUacbRPPkgBMi0SiVK2wbk8ZfbkryVYVbzhFHsSXA3B9G" -d '{ "saltNonce": "256128867579680", "owners": ["0x783110347c923b8694EF90D01D70E8f2a62b3720"], "threshold": 1 }'
> 0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e
> ```
> 
> ```
> python main.py
> 0xB7DEE4c6825b26fFe99B3c02e87FC4Cc20E99339
> ```

Good news!! The python script does return correct values. We were calling the `build_safe_create2_tx` function with one incorrect param: `fallback_handler = 0x0000000000000000000000000000000000000003` 😸 .
That means we know the parameters that the relayer is using and we can reproduce the behavior of the address prediction for the "new" accounts.
The case of the "old" accounts is different. We still don't know the params of the old prediction.

**Comment by llunaCreixent** [comment]
> Here are some scripts reproducing the problem: https://gist.github.com/adzialocha/c622ae5890deee315f658489b85bfc55. I get a different predicted safe than the one actually being used in my official Circles account:
> 
>     1. Original Safe address of user _adz_ with owner `0xaA2F8f57730d41BB145D168F6A689fDDa737a081`:
>        `0x9a0bbbbd3789f184CA88f2F6A40F42406cb842AC`
> 
>     2. Running node script returning `0xEA4e6a595B378C31cd294019b274391c7aE08aB5`
>        ```
>        $ node index.js
>        safeAddress=0xEA4e6a595B378C31cd294019b274391c7aE08aB5, nonce=175774342029441, address=0xaA2F8f57730d41BB145D168F6A689fDDa737a081
>        ```
> 
>     3. Running python script returning `0x505CcCa1d53028E6e0CDc28b4e8cA7919EA0eeAD`
>        ```
>        $ python main.py
>        0x505CcCa1d53028E6e0CDc28b4e8cA7919EA0eeAD
>        ```

And actually here the same happens. Running the python script with the corrected `fallback_handler` value, we obtain consistent but wrong results for the user _adz_: 
Both running node script or python script returning `0xEA4e6a595B378C31cd294019b274391c7aE08aB5` as the predicted address

**Comment by llunaCreixent** [comment]
@adzialocha, @ana0, do you have any hint about how we can know the values used originally by the relayer for the safe address prediction? [This](https://github.com/CirclesUBI/circles-myxogastria/issues/158#issuecomment-832783599) are the ones used nowadays.

**Comment by llunaCreixent** [comment]
The problem of the wrong safe prediction happened recently to two other users. These users where given a profile which changed before the safe was deployed (while collecting the three trust connections).

**Comment by llunaCreixent** [comment]
So I've been researching the case of one specific account. Looking into the `relay_safecreation2` table in the relayer db, I observe the following:
- Both safe addresses (the originally assigned and the one given after) have an entry.
- The entries have different values for: setup_data, payment, gas_estimated.

**Comment by llunaCreixent** [comment]
Fixed with: https://github.com/CirclesUBI/safe-relay-service/pull/50

**Comment by louilinn** [comment]
Should this be reopened? Considering this can still happen do we just handle it in other issues like https://github.com/CirclesUBI/circles-myxogastria/issues/275? Or is it completely different?

**Comment by llunaCreixent** [comment]
We can reopen it, but the problem now is related to the issue with the nonce used for the creation. I think the issue is now another, that restoring account shouldn't depend so much on the creation nonce, or that the nonce should be better calculated in the frontend.
