### ISSUE TITLE
Restoring an wallet with undeployed Safe via seed phrase leads to invalid state

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#23]
For now we display an error message to the user. This problem is not really a bug, we simply can't recover an undeployed Safe without knowing its nonce (we need this to predict the Safe address).

**Comment by adzialocha** [comment]
Solved with circles-core update: https://github.com/CirclesUBI/circles-core/commit/1b5fb9116ffdd13cbd9997d9d80d8c94124fdc92

**Comment by adzialocha** [comment]
For now we display an error message to the user. This problem is not really a bug, we simply can't recover an undeployed Safe without knowing its nonce (we need this to predict the Safe address).

**Comment by samuelandert** [comment]
When I create a new Safe with the same emailaddress, after trying to recover an undeployed safe, I still get the same Seed-Phrase. Is this correct behavior, or should it be a new one?

**Comment by adzialocha** [comment]
> .. after trying to recover an undeployed safe, I still get the same Seed-Phrase. Is this correct behavior, or should it be a new one?

The keypair is stored locally in your browser, so yeah it should keep the private key / seed phrase unless you actively deleted your keypair (thats currently only possible when closing your session in the settings).

**Comment by ana0** [comment]
One option is to also encode the nonce, so the account recover page has something like "Enter your twelve word seed phrase" and also "Enter your top secret random number" etc
